Creating storyboard page
UnBArqDsw2021-1/2021.1_G04_Cardeal pull request #13
Opened 2021-08-02 16:10 UTC by gustavoduartemoreira

STORYBOARD
Descrição
Este documento contém os desenhos de contextualização do problema.

Issue Relacionada
#8

2021-08-02 16:56 UTC, estevaoreis25 requested changes
Além das correções, gostaria que tentasse fazer um stoyboard na voisão da imobiliária ou corretores, ficaria mais completo o documento

2021-08-02 16:56 UTC, estevaoreis25 commented on docs/desenhoSoftwareBase/storyboard.md
> +O storyboard é uma técnica de sequência de desenhos ou ilustrações que podem ser utilizadas para contar uma história. É um roteiro desenhado parecido com uma história em quadrinhos. Na engenharia de
Corrigir : "desenvolivmento"

2021-08-02 16:56 UTC, estevaoreis25 commented on docs/desenhoSoftwareBase/storyboard.md
> +Entre os benfícios podemos destacar que ele apoia o planejamento para a realização do projeto, mostra visualmente as etapas.
Corrigir = "benfícios"

2021-08-02 16:56 UTC, estevaoreis25 commented on docs/desenhoSoftwareBase/storyboard.md
> +Na realização do Desing Sprint foi essa técnica foi utilizada para apoiar a elicitaçã de requisitos criando um Storyboard na visão dos funcionários da imobiliária.
Corrigir = " Desing ", " foi essa técnica foi utilizada para"(a frase nao ficou escrita adequadamente), " elicitaçã"

2021-08-02 18:07 UTC, gustavoduartemoreira commented
As correções foram feitas dá uma olhada @estevaoreis25 .

2021-08-02 18:59 UTC, gustavoduartemoreira commented
Esse storyboard é na visão dos corretores da imobiliária, eles estão conversando sobre como perderam fotos e não encontraram uma casa que queriam ai a mulher sugere criar um sistema para resolver essa situação com relatórios e filtros.

2021-08-04 01:46 UTC, marcos-mv approved these changes

2021-08-04 01:53 UTC, merged