Feature/diagrama casos de uso
UnBArqDsw2021-1/2021.1_G04_Cardeal pull request #62
Opened 2021-08-20 00:22 UTC by douglasffcastro

# Use Case Diagrams

## Descrição

Criação da documentação referente aos diagramas de Casos de Uso.

## Issue Relacionada

#53 

## Tipo de alteração

- [ ] Documentação
- [ ] Correção na Documentação

2021-08-20 21:39 UTC, gustavoduartemoreira commented
@brunocmo e @marcos-mv podem fazer o review desse ?

2021-08-20 23:53 UTC, brunocmo requested changes
Ta beleza, somente necessita a mudança do mkdocs sobre o link, e também fazer o merge com a main para não entrar em conflito.

2021-08-20 23:53 UTC, brunocmo commented on mkdocs.yml
> +           - Diagrama de Casos de Uso: modelagem/diagrama_casos_de_uso.md
Acho que só é necessário um link na seção Extras:

2021-08-21 13:30 UTC, brunocmo approved these changes

2021-08-21 13:31 UTC, brunocmo approved these changes
Tudo certo!

2021-08-21 13:31 UTC, merged